name: Auto-Merge Feature Branch to Main

# Trigger the workflow when there is a push to the feature branch
on:
  push:
    branches:
      - feature/*    # This triggers on any branch that starts with 'feature/'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Step 2: Setup GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      # Step 3: Configure Git for the Action
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      
      # Step 4: Automatically create a pull request
      - name: Create a Pull Request (PR)
        run: |
          gh pr create --title "Auto Merge from ${{ github.ref }}" --body "This PR was created automatically" --base main --head ${{ github.ref#refs/heads/ }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Approve and Merge the Pull Request automatically
      - name: Approve and Merge PR
        run: |
          pr_number=$(gh pr list --head ${{ github.ref#refs/heads/ }} --json number --jq '.[0].number')
          gh pr review $pr_number --approve
          gh pr merge $pr_number --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
