name: Auto-Merge Feature Branch to Main

on:
  push:
    branches:
      - feature/**  # Trigger for any branch starting with 'feature/'

  workflow_dispatch:  # Optional: Allows manual triggering of this workflow

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "hamzaalamlinux"
          git config --global user.email "alamhamza873@gmail.com"

      # Step 3: Merge feature branch into main
      - name: Merge Branch into Main
        run: |
          git checkout main  # Switch to the main branch
          git merge "${{ github.ref_name }}"  # Merge the feature branch into main
          git push origin main  # Push the merged changes to the main branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
